app:
  host: localhost
  port: 8080
  mode: test
  name: Test App
  version: 1.0.0
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "123456"
  etcd:
    host: "localhost"
    port: 2379