app:
  name: "chatProgram"
  mode: "dev"
  port: 9090
  version: "1.0.0"
  log:
    level: "debug"
    file_name: "app.log"
    max_size: 100
    max_backups: 10
    max_age: 30
  mysql:
    host: "8.137.19.65"
    port: 13306
    user_name: "root"
    password: "	iWyhpANxGk26ipRD"
    db_name: "my_app"
    max_open_conns: 10
    max_idle_conns: 5
  redis:
    host: "8.137.19.65"
    port: 26379
    password: "fjfstkXHwbh2ztZh"
    db: 0
    network: "tcp"
    max_idle: 300
    max_active: 500
  grpc:
    host: "8.137.19.65"
    port: 8973
    network: "tcp"