app:
  name: "chatProgram"
  mode: "dev"
  port: 9090
  version: "1.0.0"
  log:
    level: "debug"
    file_name: "app.log"
    max_size: 100
    max_backups: 10
    max_age: 30
  mysql:
    host: "mysql8019"
    port: 3306
    user_name: "root"
    password: "root"
    db_name: "my_app"
    max_open_conns: 10
    max_idle_conns: 5
  redis:
    host: "redis"
    port: 6379
    password: ""
    db: 0
    network: "tcp"
    max_idle: 300
    max_active: 500
  snowflake:
    start_time: "2006-01-02T15:04:05-07:00"
  grpc:
    host: "user-service"
    port: 8972
    network: "tcp"
  etcd:
    host: "etcd"
    port: 2379
  service:
    host: "user-service"
    port: 8972
    name: "User"
    protocol: "app"